exclude = [
    '.github',
]
line-length = 120
target-version = "py310"

[lint]
extend-select = ["E1", "E2", "E3", "E501", "W"]
ignore = ["F403", "F405"]
preview = true

[lint.per-file-ignores]
"template_code.py" = ["E501"]

[format]
quote-style = "single"
